"use client";

import "./globals.css";
import StoreProvider from "./utils/store";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div className="body-font h-screen bg-sky-50 font-ubuntu">
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
